### ISSUE TITLE
Install error: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by miloandmilk** [protoship/learn-reasonml-workshop#31] opened 2019-02-21 16:12 UTC
When running npm install I get the following:

`learn-reasonml-workshop\node_modules\bs-platform\lib\ocaml\block.cmj
fs.js:143
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:143:11)
    at Object.rename (fs.js:596:14)`

**Comment by jasim** [comment] 2019-02-27 14:54
@miloandmilk This might be a temporary network issue, an npm cache issue, or something to do with bs-platform itself. Can you try `npm uninstall bs-platform; npm install bs-platform` and see if it works?

**Comment by miloandmilk** [comment] 2019-03-04 15:45
Hi jasim, I have tried as you have suggested but to no avail. I have also deleted any signs of bs-platform and bucklescript anywhere in any npm or yarn cache! If no-one else has reported it, it still is probably environmental so the ticket may as well be closed. I can try any other suggestions you have though.

Thanks for your help!

**Comment by jasim** [comment] 2019-03-04 18:25
@miloandmilk I couldn't reproduce any errors, but I've anyway upgraded bs-platform to the latest version and checked in package-lock.json as well. Can you clone the repo to a new directory, run `npm install`, and see how it goes?

If you still get errors, could you attach your entire `npm install` log so that I can get more context? I've tested this only on OS X, and other students have used it on Linux without issues. I'm not sure about Windows support if you're on that.

**Comment by jasim** [comment] 2019-03-11 19:04
Closing this issue for now.

**Closed as completed by jasim** 2019-03-11 19:04 UTC
